version: '3.4'
services:
    react-nginx-app:
      stdin_open: true
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
          - '.:/usr/src/app'
          - /usr/src/app/node_modules
      expose:
        - 8080
      ports:
        - 8080:80
      environment:
          - CHOKIDAR_USEPOLLING=true